/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daw;

import com.fasterxml.jackson.core.JsonProcessingException;
import conexion_http.ConexionHTTP;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import modelos.Carbono;
import serviciojson.JsonService;

/**
 *
 * Enlaces para probar:
 * -Normal: www.riverford.co.uk/
 * -Bueno: rights4children.org.uk/
 * -Mal: maralboran.eu
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        setResizable(false);
        setTitle("Medidor de huella de carbono");
        botonBusqueda.setFocusPainted(false);
        botonBusqueda.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        botonBusqueda = new javax.swing.JButton();
        textoRuta = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        labelGif = new javax.swing.JLabel();
        labelTexto = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 216, 211));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBusqueda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        botonBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nubeBoton.png"))); // NOI18N
        botonBusqueda.setText("Buscar");
        botonBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });
        panelPrincipal.add(botonBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 160, 50));

        textoRuta.setBackground(new java.awt.Color(255, 215, 228));
        textoRuta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        textoRuta.setForeground(new java.awt.Color(153, 153, 153));
        textoRuta.setText("Introduce una URL...");
        textoRuta.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        textoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRutaActionPerformed(evt);
            }
        });
        panelPrincipal.add(textoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 427, 50));

        labelTitulo.setBackground(new java.awt.Color(58, 58, 58));
        labelTitulo.setFont(new java.awt.Font("Chilanka", 1, 28)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("MEDIDOR DE HUELLA DE CARBONO");
        panelPrincipal.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 520, 52));

        labelGif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nubes.gif"))); // NOI18N
        panelPrincipal.add(labelGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 6, -1, 184));

        labelTexto.setFont(new java.awt.Font("Chilanka", 0, 22)); // NOI18N
        labelTexto.setForeground(new java.awt.Color(58, 58, 58));
        labelTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTexto.setText("<html> <p>Las búsquedas en internet requieren de </p> <p>cierta energía y algunas de ellas consumen <p> mucha, lo que genera contaminación.</p> <p>Inserta el enlace de una página y te  </p> <p>mostraremos la huella de carbono que</p> <p>deja tu búsqueda.</p> </html> ");
        panelPrincipal.add(labelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 695, 197));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        panelPrincipal.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed

        final String LINK = "https://api.websitecarbon.com/site?url=";
        //El texto que introduce el usuario en el text field
        String ruta = this.textoRuta.getText();
        String ultimo = LINK + ruta;

        String http = null;
        try {
            //Guarda en el string el contenido de la página web introducida que tiene 
            //formato json
            http = ConexionHTTP.peticionHttpGet(ultimo);
        } catch (IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            //json obtenido del enlace anterior
            Carbono carbono = (Carbono) JsonService.stringToPojo(http, Carbono.class);
            //Método que modifica el panel según el resultado del json
            modificarPanel(carbono, ruta);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void modificarPanel(Carbono carbono, String ruta){
        
        // Variables de cada imagen 
        ImageIcon fondoMalo = new ImageIcon("src/main/resources/img/fondoMalo.png");
        ImageIcon fondoNormal = new ImageIcon("src/main/resources/img/fondoNormal.png");
        ImageIcon fondoBueno = new ImageIcon("src/main/resources/img/fondoBueno.png");
        ImageIcon imgNubeNormal = new ImageIcon("src/main/resources/img/nubeNormal.png");
        ImageIcon imgNubeTriste = new ImageIcon("src/main/resources/img/nubeTriste.png");
        ImageIcon imgNubeFeliz = new ImageIcon("src/main/resources/img/nubeFeliz.png");
       
        
        if (carbono.getCleanerThan() <= 0.33) {
                // Esto significa que es malo
                //Cambio del fondo y de la imagen del panel
                labelGif.setIcon(imgNubeTriste);
                labelFondo.setIcon(fondoMalo);
               
                labelTitulo.setForeground(Color.black);
                labelTexto.setForeground(Color.DARK_GRAY);
                
                textoRuta.setBackground(new Color(54, 223, 196));
                textoRuta.setForeground(Color.DARK_GRAY);
               
                //Redondeo de los gramos emitidos por la búsqueda
                double redondeo = (double)(Math.round(carbono.getStatistics().getCo2().getGrid().getGrams()*100))/100;
                // StringBuilder para cambiar el mensaje de texto del labelTexto
                StringBuilder sb = new StringBuilder();
                sb.append("<html><body>");
                sb.append(ruta);
                sb.append("<br>Está página contamina más que el ");
                sb.append("<span style='color: red;'><b>");
                sb.append(100 - carbono.getCleanerThan()*100);
                sb.append(" %</b></span>");
                sb.append(" del resto de páginas testeadas<br>");
                sb.append("En esta página se ha consumido: <br> <span style='color: red;'><b>");
                sb.append(redondeo);
                sb.append("</b></span> gramos de CO2<br><br>");
                sb.append("<span style='color: red;'><b>Esta página contamina más que el resto</b></span>");
                sb.append("</body></html>");
               
                labelTexto.setText(sb.toString());
               
            } else if (carbono.getCleanerThan() > 0.33 && carbono.getCleanerThan() <= 0.66) {
                // Esto significa que es normal
                //Cambio del fondo y de la imagen del panel
                labelFondo.setIcon(fondoNormal);
                labelGif.setIcon(imgNubeNormal);
                labelTexto.setBackground(Color.red);
                textoRuta.setBackground(new Color(247, 196, 164));
                textoRuta.setForeground(Color.DARK_GRAY);
               
                //Redondeo de los gramos emitidos por la búsqueda
                double redondeo = (double)(Math.round(carbono.getStatistics().getCo2().getGrid().getGrams()*100))/100;
                // StringBuilder para cambiar el mensaje de texto del labelTexto
                StringBuilder sb = new StringBuilder();
                sb.append("<html><body>");
                sb.append(ruta);
                sb.append("<br>Está página contamina más que el ");
                sb.append("<span style='color: yellow;'><b>");
                sb.append(100 - carbono.getCleanerThan()*100);
                sb.append(" %</b></span>");
                sb.append(" del resto de páginas testeadas<br>");
                sb.append("En esta página se ha consumido: <br><span style='color: yellow;'><b>");
                sb.append(redondeo);
                sb.append("</b></span> gramos de CO2<br><br>");
                sb.append("<span style='color: yellow;'><b>Esta página contamina igual que el resto<b></span>");
                sb.append("</body></html>");
               
                labelTexto.setText(sb.toString());
               
            } else {
                // Esto significa que está bueno
                labelFondo.setIcon(fondoBueno);
                labelGif.setIcon(imgNubeFeliz);
                labelGif.setSize(275, 275);
               labelTexto.setBackground(Color.red);
               
                 //Redondeo de los gramos emitidos por la búsqueda
                double redondeo = (double)(Math.round(carbono.getStatistics().getCo2().getGrid().getGrams()*100))/100;
                // StringBuilder para cambiar el mensaje de texto del labelTexto
                StringBuilder sb = new StringBuilder();
                sb.append("<html><body>");
                sb.append(ruta);
                sb.append("<br>Está página contamina más que el ");
                sb.append("<span style='color: green'><b>");
                sb.append(100 - carbono.getCleanerThan()*100);
                sb.append(" %</b></span>");
                sb.append(" del resto de páginas testeadas<br>");
                sb.append("En esta página se ha consumido: <br><span style='color: green;'><b>");
                sb.append(redondeo);
                sb.append("</b></span> gramos de CO2<br><br>");
                sb.append("<span style='color: green;'><b>Esta página contamina muy poco comparado con el restol<b></span>");
                sb.append("</body></html>");
               
                labelTexto.setText(sb.toString());
            }
    }
    
    private void textoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRutaActionPerformed
        
    }//GEN-LAST:event_textoRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JLabel labelFondo;
    public static javax.swing.JLabel labelGif;
    private javax.swing.JLabel labelTexto;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField textoRuta;
    // End of variables declaration//GEN-END:variables
}
