/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daw;

import com.fasterxml.jackson.core.JsonProcessingException;
import conexion_http.ConexionHTTP;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import modelos.Carbono;
import serviciojson.JsonService;

/**
 *
 * @author Alejandro
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        textoRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 216, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 87, 36));

        textoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRutaActionPerformed(evt);
            }
        });
        jPanel1.add(textoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 427, 36));

        jLabel2.setFont(new java.awt.Font("Chilanka", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("MEDIDOR DE HUELLA DE CARBONO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 520, 52));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/picasion.com_a0e15f751bcae3afd3bf6747bef17e1b.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 6, -1, 184));

        jLabel4.setFont(new java.awt.Font("Chilanka", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("<html> <p>Las busquedas en internet requieren de </p> <p>cierta energía y algunas de ellas consumen <p> mucha, lo que genera contaminación.</p> <p>Inserta el enlace de una página y te  </p> <p>mostraremos la huella de carbono que</p> <p>deja tu búsqueda.</p> </html> ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 75, 695, 197));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        final String LINK = "https://api.websitecarbon.com/site?url=";
        final String LINK2 = "https://api.websitecarbon.com/site?url=www.";
        String ruta = this.textoRuta.getText();
        String ultimo;
        // Variables de cada imagen 
        ImageIcon imagenMalo = new ImageIcon("src/main/resources/img/sarkani.png");
        ImageIcon imagenNormal = new ImageIcon(".png");
        ImageIcon imagenBueno = new ImageIcon(".png");
        ImageIcon imagenFondoMalo = new ImageIcon(".png");
        
        if (ruta.substring(0, 4).equals("www.")) {
            ultimo = LINK + ruta;
        } else {
            ultimo = LINK2 + ruta;
        }

        String http = null;
        try {
            http = ConexionHTTP.peticionHttpGet(ultimo);
        } catch (IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Carbono carbono = (Carbono) JsonService.stringToPojo(http, Carbono.class);

            if (carbono.getCleanerThan() <= 0.33) {
                // Esto significa que es muy malo
                jLabel3.setIcon(imagenMalo);
                //jLabel5.setIcon(imagenDeFondoMalo);
                
                // StringBuilder para cambiar el mensaje de texto del label4
                double grPor10 = carbono.getStatistics().getCo2().getGrid().getGrams()*100;
                double redondeao = Math.round(grPor10);
                double redondea2 = redondeao/100;
                StringBuilder sb = new StringBuilder();
                sb.append("<html><body>");
                sb.append(ruta);
                sb.append("<br>Está página contamina más que el ");
                sb.append(100 - carbono.getCleanerThan()*100);
                sb.append("% que el resto de páginas testeadas<br>");
                sb.append("En esta página se ha consumido: <br>");
                sb.append(redondea2);
                sb.append(" gramos de CO2<br>");
                sb.append("<span style='color: red;'>Esta página tiene un alto impacto ambiental</span>");
                sb.append("</body></html>");
                
                jLabel4.setText(sb.toString());
                
            } else if (carbono.getCleanerThan() > 0.33 && carbono.getCleanerThan() <= 0.66) {
                // Esto significa que es normal
                
                
                // StringBuilder para cambiar el mensaje de texto del label4
                double grPor10 = carbono.getStatistics().getCo2().getGrid().getGrams()*100;
                double redondeao = Math.round(grPor10);
                double redondea2 = redondeao/100;
                StringBuilder sb = new StringBuilder();
                sb.append("<html><body>");
                sb.append(ruta);
                sb.append("<br>Está página contamina más que el ");
                sb.append(100 - carbono.getCleanerThan()*100);
                sb.append("% que el resto de páginas testeadas<br>");
                sb.append("En esta página se ha consumido: <br>");
                sb.append(redondea2);
                sb.append(" gramos de CO2<br>");
                sb.append("<span style='color: red;'>Esta página tiene un alto impacto ambiental</span>");
                sb.append("</body></html>");
                
                jLabel4.setText(sb.toString());
                
                
            } else {
                // Esto significa que está bueno
                
                
                 // StringBuilder para cambiar el mensaje de texto del label4
                double grPor10 = carbono.getStatistics().getCo2().getGrid().getGrams()*100;
                double redondeao = Math.round(grPor10);
                double redondea2 = redondeao/100;
                StringBuilder sb = new StringBuilder();
                sb.append("<html><body>");
                sb.append(ruta);
                sb.append("<br>Está página contamina más que el ");
                sb.append(100 - carbono.getCleanerThan()*100);
                sb.append("% que el resto de páginas testeadas<br>");
                sb.append("En esta página se ha consumido: <br>");
                sb.append(redondea2);
                sb.append(" gramos de CO2<br>");
                sb.append("<span style='color: red;'>Esta página tiene un alto impacto ambiental</span>");
                sb.append("</body></html>");
                
                jLabel4.setText(sb.toString());
            }

        } catch (JsonProcessingException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void textoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoRuta;
    // End of variables declaration//GEN-END:variables
}
